# Trigger the pipeline when changes are pushed to the 'main' branch
trigger:
- main 

pool:
  vmImage: 'windows-latest' 

variables:
  azureSubscription: 'AzureSPConnection'  # Name of the service connection to authenticate with Azure
  resourceGroupName: 'MonitoringRG'  # Name of the resource group containing the VM and Log Analytics workspace
  workspaceName: 'MonitoringWorkspace'  # Name of the Log Analytics workspace
  vmName: 'MyMonitoringVM'  # Name of the Virtual Machine to be monitored

# Define the steps of the pipeline
steps:

# Step 1: Run Azure CLI commands to interact with Azure resources
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      
      # PowerShell command to check if the Log Analytics workspace exists
      az monitor log-analytics workspace show --resource-group $(resourceGroupName) --workspace-name $(workspaceName)


# Step 2: Install and configure the Microsoft Monitoring Agent (MMA) on the Windows VM
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      
      # Define the JSON settings as variables
      $publicSettings = '{\"workspaceId\":\"aeb0ff90-63af-49c8-95ee-c86dbb105b40\"}'
      $protectedSettings = '{\"workspaceKey\":\"uTTMvs/CQCkjAxQOOJEd1oYvaUvtMtcxlW6yqC3uAXo6/mDZQODO8DcRvFJ8rHIDjz6oJYocianNGPgsPR36bg==\"}'
    
      
      # Install the Microsoft Monitoring Agent (MMA) on the Windows VM
      # This agent collects data from the VM and sends it to the Log Analytics workspace
      az vm extension set `
        --resource-group $(resourceGroupName) `
        --vm-name $(vmName) `
        --name MicrosoftMonitoringAgent `
        --publisher Microsoft.EnterpriseCloud.Monitoring `
        --settings $publicSettings `
        --protected-settings $protectedSettings 
